language: ruby
cache: bundler

sudo: false

branches:
  only:
    - master
    - 8-stable

before_install:
  - gem update --system
  - gem --version
  - gem uninstall bundler -a -x -I
  - rvm @global do gem uninstall bundler -a -x -I
  - gem install bundler
  - bundle --version
  - rm -f .bundle/config
rvm:
  - 2.1.9
  - 2.2.6
  - 2.3.3
  - ruby-head

allow_failures:
  - rvm: ruby-head

script:
  - bundle exec chefstyle
  - bundle exec rake spec
  - bundle exec ohai
